### ISSUE TITLE
Feature: option to save deviceId for tab's domain

### ISSUE THREAD

**Issue by kawazoe** [ish-/AuRo#2] opened 2022-05-20 19:39 UTC
I use this extension for the Tidal PWA on Brave (linux) and I noticed that it doesn't seem to remember my selection when the tab is closed and re-opened. It would be nice if there was a way to remember the device I pick (based on the domain maybe?) and re-apply the setting automatically.

EDIT: This appears to be caused by the fact that tab ids, which are used to store the selection, in Brave aren't stable, so trying to query for a previous selection for the tab always yields an incorrect result.

**Comment by ish-** [comment] 2022-05-20 20:06
@kawazoe its implemented already (https://github.com/ish-/AuRo/blob/main/extension/background.js#L28)
i think the problem is "privateness" of Brave browser, check it in Chrome

**Comment by kawazoe** [comment] 2022-05-20 20:53
@ish- I think I know what's going on. When I query the storage I get a bunch of values like this:

> tab_137: "1c560f8a96130cfb42b802ff9dc75f30bffdcaddcb9e41c0dadb40e70b6329a6"
> tab_2306: "1c560f8a96130cfb42b802ff9dc75f30bffdcaddcb9e41c0dadb40e70b6329a6"

After closing the PWA and reopening it again (not with ctrl+shift+T), I got yet a new id. My conclusion is that the `tab.id` you're getting from `chrome.tabs.query()` isn't stable, at least not in Brave.

**Comment by ish-** [comment] 2022-05-20 21:42
@kawazoe exactly, you're right, i look at code now and remembered commented code `hostDeviceId` wasn't stable =)
i'll try to continue development on the week i think

**Comment by ish-** [comment] 2022-06-05 18:01
@kawazoe hello! i committed this feature here at first, maybe you would try it locally for some days and feedback :)
https://github.com/ish-/AuRo/commit/6a77c55624100cf18ea22e6bf044607ccb1179eb

**Comment by kawazoe** [comment] 2022-06-05 21:44
Sure! Can you give me some info on how to package the code into the final extension?

**Comment by ish-** [comment] 2022-06-06 10:05
@kawazoe thank you!
To add extension locally, you should turn on developer mode in extensions, then click "Load unpacked" and select it from your disk

**Comment by kawazoe** [comment] 2022-06-06 21:15
So far, it seems to be working flawlessly! I'll keep running the extension in dev mode for now. You can close the issue when you release the update so I know I can switch back to the official release. :smiley:

**Comment by ish-** [comment] 2022-06-06 21:20
@kawazoe oh, nice to hear it =) ill upload it over the next few days
thank you!

**Comment by kawazoe** [comment] 2022-06-12 01:03
Small update, the domain safe fix has survived through multiple browsers restarts, full OS reboots, two full system update, running multiple instances of the same tab at once, etc. Seems pretty solid to me.

**Closed** 2022-12-13 12:54 UTC
